### ISSUE TITLE
di no existe, creo que querías poner div

### ISSUE THREAD

**Issue by valfrio** [iesgrancapitan-entornos/2023-24-pr-ctica-5-github-issues-oscarmcc#3]
https://github.com/iesgrancapitan-entornos/2023-24-pr-ctica-5-github-issues-oscarmcc/blob/ab2289fb46f826d93853b4ecd279777238bb4817/index.html#L11

**Comment by oscarmcc** [comment]
q debo hacer

**Comment by valfrio** [comment]
poner div
